qlik-oss/sn-list-objects

.gitignore
packages/sn-filter-pane/core/package.json
packages/sn-filter-pane/package.json
packages/sn-filter-pane/src/hooks/style.scss
packages/sn-filter-pane/src/hooks/use-render.ts
packages/sn-listbox/core/package.json
packages/sn-listbox/package.json
packages/sn-listbox/src/index.ts
packages/sn-listbox/yarn.lock

Make the sn-filter-pane ready for alpha release:
- Expose a `/core/esm` (also added to sn-listbox) since this is a standard for other viz packages
- Minor clean up

chore(sn-filter-pane, sn-listbox): prepare for alpha release

---

packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts

test: add unit tests to grid layout

---

packages/sn-filter-pane/src/components/ExpandButton.tsx
packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/components/ListboxGrid/interfaces.ts
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

feat: popover container

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/hooks/types/index.d.ts
packages/sn-filter-pane/src/hooks/use-setup.ts
packages/sn-filter-pane/src/store/index.ts
packages/sn-listbox/src/index.ts

https://user-images.githubusercontent.com/13185716/206464392-8af9e425-96d7-4ef9-b3b8-ad7f0599d081.mov

feat: add direction listboxOptions

---

packages/sn-listbox/src/ext/property-panel/index.ts
packages/sn-listbox/src/index.ts
packages/sn-listbox/src/object-properties.ts

Throws an error because `frequencyMode` is not allowed as an option when using existing model.

fix: frequecyMode in sn-listbox

---

packages/sn-filter-pane/src/ext/property-panel/data/index.ts
packages/sn-filter-pane/src/qae/listbox-properties.ts
packages/sn-listbox/src/object-properties.ts

feat: add wildcard property

---

packages/sn-filter-pane/package.json
packages/sn-filter-pane/src/components/ExpandButton.tsx
packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx
packages/sn-filter-pane/src/components/__tests__/ListboxPopoverContainer.spec.tsx
packages/sn-filter-pane/src/components/root.tsx
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/index.ts
packages/sn-filter-pane/src/hooks/use-render.ts
packages/sn-filter-pane/src/hooks/use-setup.ts
packages/sn-filter-pane/src/index.ts
packages/sn-filter-pane/src/qae/data.ts
packages/sn-filter-pane/src/store/index.ts

fix: create stores for each filterpane

---

.github/workflows/build-test-single.yml
packages/sn-listbox/package.json

It looks like it did not run the new steps in the build for this PR.
maybe need to be merged to run?

chore: verify types in workflow

---

packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxContainer.tsx

Solves #58 
Change search option from `inSelection` to `toggle`: https://github.com/qlik-oss/nebula.js/pull/1112

feat: truncate title, use toggle search

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/store/index.ts

fix: get isSmallSize from sense

---

packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx

Fixed RTL Mode for Folded List Box & Columns inside filter pane. Fixes issue : https://github.com/qlik-oss/sn-list-objects/issues/82

fix(filter-pane): rtl mode

---

packages/sn-filter-pane/src/ext/conversion/list-object-util.ts

fix #134 (only missing title not console errors)

fix: set title on correct property on conversion

---

packages/sn-filter-pane/src/ext/property-panel/data/data-panel/update-frequency-max.ts

fix #135 (when combined with qlik-oss/nebula.js#1152)

feat: mark frequencyMax for master dim to be fetched later

---

packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

This PR fixes two issues :- 
https://github.com/qlik-oss/sn-list-objects/issues/126
https://github.com/qlik-oss/sn-list-objects/issues/125

fix: remove resize and increase width of the popover

---

packages/sn-filter-pane/src/ext/property-panel/data/data-panel/index.ts

fix: fields label

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/index.ts
packages/sn-listbox/src/object-properties.ts

feat: add show title checkbox to pp

---

packages/sn-filter-pane/src/ext/property-panel/settings.ts

fix: remove labels from simple properties

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/services/render-tracker.ts
test/integration/index.spec.js

fix: resolve render tracker if zero listboxes

---

packages/sn-filter-pane/src/ext/property-panel/index.ts
packages/sn-filter-pane/src/ext/property-panel/simple-sorting.ts

feat: add sorting in simple edit mode

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx

fix: check theme if object should have borders

---

packages/sn-filter-pane/src/components/FoldedListbox/FoldedListbox.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/keys.ts
packages/sn-filter-pane/src/hooks/use-focus-listener.ts

This is to fix https://github.com/qlik-oss/sn-list-objects/issues/232.

fix: support keyboard navigation for collapsed mode

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx
packages/sn-filter-pane/src/hooks/use-focus-listener.ts

fix: fix Enter get stuck

---

packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

fix: scroll when needed in more fields popover

---

packages/sn-filter-pane/src/components/ListboxGrid/ConditionalWrapper.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx

feat: remove development mode resize element

---

.github/workflows/api-gov.yml
.github/workflows/build-test.yml
.github/workflows/create-release.yaml
.release-it.json
package.json
scripts/get-pre-next-version.js
yarn.lock

*set bumped version in `packages/sn-filter-pane/api-spec/spec.json` and in build-artifacts from release workflow.
*run api-gov workflow to update baseline from release workflow.
*run api-gov workflow to verify api from build-test workflow.

chore: set version in api and build after bump

---

examples/filterpane-dev-mashup/package.json
examples/filterpane-dev-mashup/yarn.lock
packages/sn-filter-pane/core/package.json
packages/sn-filter-pane/package.json
packages/sn-listbox/core/package.json
packages/sn-listbox/package.json

stardust 4.7.0 (peer deps mainly)

chore: bump to stardust 4.7.0

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx
packages/sn-filter-pane/src/utils/reset-zoom.ts

Patch for 0.13.x fixing reset zoom on iPhone for all known scenarios.

fix(sn-filter-pane): reset zoom for all scenarios (#392)

---

packages/sn-filter-pane/src/hooks/listbox/get-listbox-resources.ts
packages/sn-filter-pane/src/hooks/use-render.ts

When having filter pane in analysis mode and then go to Load data edit to reload data I get the below error

fix: prevent memory leak error

---

packages/sn-filter-pane/src/locale/locales/de.json
packages/sn-filter-pane/src/locale/locales/es.json
packages/sn-filter-pane/src/locale/locales/fr.json
packages/sn-filter-pane/src/locale/locales/it.json
packages/sn-filter-pane/src/locale/locales/ja.json
packages/sn-filter-pane/src/locale/locales/ko.json
packages/sn-filter-pane/src/locale/locales/nl.json
packages/sn-filter-pane/src/locale/locales/pl.json
packages/sn-filter-pane/src/locale/locales/pt.json
packages/sn-filter-pane/src/locale/locales/ru.json
packages/sn-filter-pane/src/locale/locales/sv.json
packages/sn-filter-pane/src/locale/locales/tr.json
packages/sn-filter-pane/src/locale/locales/zh-CN.json
packages/sn-filter-pane/src/locale/locales/zh-TW.json

chore(translations): UI bus - 2024-05-03
- Update translations related to: e75e3d5 - fix: add cyclic icon and update drilldown icon (#424)

chore(translations): UI bus - 2024-05-03

---

packages/sn-filter-pane/src/hooks/use-styling/selections-style.ts

aligning the color with other parts of the UI

fix: correct green color

---

packages/sn-filter-pane/src/ext/property-panel/settings/presentation/styling-panel-def.ts
packages/sn-filter-pane/src/ext/property-panel/settings/presentation/styling-utils/font-utils.js

To fix broken filterpane in qlik-embed when the feature flag IM_4073_FILTERPANE_STYLING is on.

fix: check if theme available

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx

needs qlik-oss/nebula.js#1613 to work

fix: use disbalePortal option to fix more menu
