packages/sn-filter-pane/src/data/index.ts
packages/sn-filter-pane/src/hooks/use-render.ts
packages/sn-filter-pane/src/types/types.d.ts

Changes:
- Prevent re-rendering each time layout changes Fix(#7)
- Clean up, add types and remove code for unneeded dimension operations (we only need `add` and `remove`)

refactor: prevent flickering and cleaning up

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/root.tsx
packages/sn-filter-pane/src/hooks/use-render.ts
packages/sn-filter-pane/src/store/index.ts

To get updated `resources` when `useRender()` fires and avoid trigger `render()` we save the latest resources in the store.
Fixes #25

feat: use resource store

---

packages/sn-filter-pane/src/ext/conversion/index.ts
packages/sn-filter-pane/src/ext/conversion/list-object-util.ts
packages/sn-filter-pane/src/ext/conversion/object-conversion.ts
packages/sn-filter-pane/src/ext/conversion/types.ts
packages/sn-filter-pane/src/ext/index.ts

Add logic for importing properties and export properties for chart conversion in sn-filter-pane
https://user-images.githubusercontent.com/13185716/215098139-f836d77d-2335-47b8-ae12-2a8dfda0d8b5.mov

feat: import&export properties chart conversion

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/hooks/use-render.ts

Hide search input by default, as per UX designs. Fixes #8

feat: toggle search

---

.editorconfig
packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/__tests__/distribute-resources.spec.ts
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/components/ListboxGrid/use-handle-active.ts
packages/sn-filter-pane/src/ext/property-panel/data/index.ts
packages/sn-filter-pane/src/hooks/types/index.d.ts
packages/sn-filter-pane/src/hooks/use-setup.ts
packages/sn-filter-pane/src/store/index.ts
types/global.d.ts

*Propagate selection event from Listbox to sense-client (By keeping track of selection states for listboxes). To show hide context menu in sense-client.
*Update size of Listbox
*Disable search in Listbox if it contains 3 items or less
*Update property-panel to show/hide title(toolbar) in Listbox. Take hidden title in account in `distribue-resources.ts`

feat: signal selection event to sense-client

---

packages/sn-filter-pane/src/qae/data.ts

To fix https://github.com/qlik-oss/sn-list-objects/issues/48 by setting the minimum number of dimensions to 1 to make it the same to the old filter pane.

fix: set minimum number of dimensions to 1

---

packages/sn-filter-pane/src/ext/property-panel/data/data-panel/presentation/index.ts

Two VF fixes for grid mode:
- Ensure auto getter has a fallback to `true` when deciding on showing the row/col numbers fixes(https://github.com/qlik-oss/sn-list-objects/issues/91)
- Ensure `layoutOrder` always has a value in grid mode fixes(https://github.com/qlik-oss/sn-list-objects/issues/88)

fix: grid mode fixes

---

packages/sn-filter-pane/src/hooks/listbox/get-listbox-resources.ts
packages/sn-filter-pane/src/hooks/types/index.d.ts

On selection, there is no need to send getProperties to engine. This will improve the performance of render a listbox on selection.

fix: remove getProperties request on selection

---

packages/sn-filter-pane/src/ext/index.ts

This is to fix https://github.com/qlik-oss/sn-list-objects/issues/132 and https://github.com/qlik-oss/sn-list-objects/issues/131 by adding getDropFieldOptions and getDropMeasureOptions to sn-filter-pane.

fix: fix drop filed/measure to a filter pane

---

packages/sn-filter-pane/src/ext/property-panel/data/data-panel/__test__/update-frequency-max.spec.ts
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/index.ts
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/presentation/index.ts
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/update-frequency-max.ts

This PR is to fix frequency max in case of a calculated dimension which uses ]. It also trigger an update for frequency max on relating change like a field being changed or histogram option being changed or frequency option being changed.

fix: update frequency max on relating change

---

packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

Fallback to mui background color if filterpane background is transparent or undefined, for popover

fix: don't use transparent background for popover

---

packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

ListBox popover opens in a full window when clicked. Fixes : https://github.com/qlik-oss/sn-list-objects/issues/162

fix: small screen listbox popover opens as a full window

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

Popover is also closed with Esc and Enter corresponding to Cancel and Confirm selections respectively. Fixes : https://github.com/qlik-oss/sn-list-objects/issues/160
https://user-images.githubusercontent.com/30860406/226853272-3ad7bb62-42d3-44d0-8bc7-7f24bc9551ea.mp4

fix: close popover when selections confirmed or cancelled

---

packages/sn-filter-pane/src/components/ListboxContainer.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx
packages/sn-filter-pane/src/ext/property-panel/data/data-panel/presentation/index.ts
packages/sn-filter-pane/src/hooks/direct-query/dq-properties-utils.ts
packages/sn-filter-pane/src/hooks/direct-query/is-direct-query-enabled.ts
packages/sn-filter-pane/src/hooks/direct-query/json-patch.js
packages/sn-filter-pane/src/hooks/direct-query/soft-property-handler.js
packages/sn-filter-pane/src/hooks/direct-query/use-direct-query.js
packages/sn-filter-pane/src/hooks/types/index.d.ts
packages/sn-filter-pane/src/hooks/use-setup.ts
packages/sn-filter-pane/src/index.ts
packages/sn-filter-pane/src/store/index.ts
packages/sn-filter-pane/tsconfig.json
packages/sn-listbox/tsconfig.json
types/global.d.ts

Move the logic previously residing in sense-client, into Filter pane so that we can [soon] completely replace the Angular Filter pane there.
To be added (probably in another PR): Unit tests.

feat(sn-filter-pane): Support Direct Query

---

packages/sn-filter-pane/src/qae/listbox-properties.ts
packages/sn-listbox/src/object-properties.ts

Changes default setting of `disableNavMenu` which is the "hover menu" within Qlik Sense. This decision was taken after discussions with UX to mitigate problems with hover menu overlapping important things in the UI.

refactor: disable qlik sense navmenu by default

---

packages/sn-filter-pane/src/components/ListboxGrid/use-handle-resize.ts

Prevent the last item from being hidden when height is small and multiple columns.

fix: prevent hidden item

---

packages/sn-filter-pane/src/components/ExpandButton.tsx
packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxGrid/distribute-resources.ts
packages/sn-filter-pane/src/components/ListboxGrid/use-handle-resize.ts

- Ensure wrapping/expand button's color is kept on hover (previously overridden by mui's style on hover)
- ~Expand the last listbox item in first column to fill out the remaining space (this is how it worked before introducing `collapseMode`)~
https://github.com/qlik-oss/sn-list-objects/assets/5780544/01c326e6-2061-4342-a158-969709d47c86

fix: hover color and expand last item

---

packages/sn-filter-pane/src/ext/property-panel/settings/presentation/styling-panel-def.js
packages/sn-filter-pane/src/hooks/styling-utils.ts
packages/sn-filter-pane/src/hooks/types/components.d.ts

Conform to nebulas naming of background image properties (not using naming as in e.g. ActionButton) as it is confusing to have two different ways of implementing the same thing.

fix(sn-filter-pane): conform to nebulas naming of background image properties

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx
packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx
packages/sn-filter-pane/src/utils/reset-zoom.ts

When opening the search field on a mobile device (iOS), the browser zooms in, hiding parts of the listbox and search field.
This has been fixed before with https://github.com/qlik-oss/sn-list-objects/pull/365 but not covering all scenarios.
The previous fix called the new utility function `resetZoom()` when opening up a folded listbox. This ignored that scenario where we don't have a folded listbox from the start.
In this fix, `resetZoom()` is called when focusing the Filter pane container itself. It is still called only on small devices (as defined by Sense). In the tests (see example in screen recording) it works fine and is not called extensively either.
https://github.com/qlik-oss/sn-list-objects/assets/5780544/6b43cfed-df7a-4121-a184-4b59f9c39b18

fix(sn-filter-pane): reset zoom for all scenarios

---

packages/sn-filter-pane/src/ext/property-panel/settings/presentation/styling-panel-def.ts
packages/sn-filter-pane/src/hooks/types/components.d.ts

The reset button in the background section currently resets all Listbox styling settings.
Added a reset function for this subsection to handle reset explicitly (resetting the `themeComponent.background` object).
Also added missing TS types.

fix(sn-filter-pane): move background definition so reset only affects this setting

---

packages/sn-filter-pane/src/components/ListboxPopoverContainer.tsx

Currently, the mui popover modifies the body tag with `overflow: hidden` and `padding-right: 17px` on Windows, to compensate for the scrollbar. This can be disable with: `disableScrollLock`. Since we use a backdrop that prevents interactions, there should not be any side-effects that I can think of.

fix(sn-filter-pane): disable popover messing with body tag

---

packages/sn-filter-pane/src/hooks/listbox/get-listbox-resources.ts
packages/sn-filter-pane/src/hooks/use-render.ts

fix that update in child listboxes did not update the filterpane
Selection & Header for folded listboxes
and anything that affected layout & if the listbox should be collapsed (ex: Collapse Listbox setting)
some rist of performance degrade as there are more update that make it re-render

fix: update then child object layout changes

---

packages/sn-filter-pane/src/hooks/listbox/get-listbox-resources.ts

keyboard navigation in filterpane break without it.

fix: also trigger update if all child objects have layout but are not changed

---

packages/sn-filter-pane/src/hooks/use-setup.ts
packages/sn-filter-pane/src/hooks/use-styling/__tests__/selection-style.spec.ts
packages/sn-filter-pane/src/hooks/use-styling/selections-style.ts
packages/sn-filter-pane/src/hooks/use-styling/types.d.ts
packages/sn-filter-pane/src/hooks/use-styling/use-styling.ts

Enabling selection colors from dataColors. This is behind feature flag

feat: use selection colors from theme

---

packages/sn-filter-pane/src/components/ListboxGrid/ListboxGrid.tsx

When using filterpane in mashup with `keyboard.enabled = false` we want to let the keyboard navigation being handled by default webbrowser handler. preventDefault on on key events that are not handled by this component prevent default behaviour from working properly. 
Example on this is when user tabs to navigate to different listboxes. Without this fix user can't tab pass the row of first listbox.

fix: should not preventDefaultBehaviour on keys that are not handled by the component
